apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verifyng-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: verifyng-storage
